[env]
TERM = "xterm-256color"

[font]
normal = { family = "DepartureMono Nerd Font Mono", style = "Regular" }
offset = { x = 1, y = 2 }
size = 15

[shell]
program = "/bin/zsh"

[window]
blur = true
decorations = "Buttonless"
opacity = 0.7
option_as_alt = "Both"
startup_mode = "Maximized"
